version: "2.1"
services:
  rtmp-server:
    image: dreckrtmp:latest
    restart: always
    depends_on:
      - api
    environment:
      ON_PUBLISH: http://api:8000/onpublish
      ON_PUBLISH_DONE: http://api:8000/onpublish/done
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "1935:1935"
  api:
    image: dreckrtmpapi:latest
    restart: always
    volumes:
      - ./api/api:/app/api
