[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["now <now@tutao.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
starlite = "^1.41.0"
uvicorn = "^0.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
